MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.16

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,12 +7,20 @@ os: osx
 osx_image: xcode6.4
 
 env:
+  matrix:
+    - CONFIG=osx_
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "3Rux1FVEgd93+36m2amKu1Kztuufqyk/CLXcOAXk8IMCZ697KFKuU3IKcyixL468bhGQwzAu8S7t+up5BmWCkAz5a++JfGVegOTjTdsEu5uTu/tdgnkY5GHSPpyKEokwv8s87q8vWdgGEiF7GJ+vQD6LqD4DS0rCQf/gdKk8pMtVScdEf1ynKxBZeWESR5U2F9qpw41S5XdNr3z6wVxorRAr107NMMhthQTAGXQFAdw9JX/WiQdET6jRt8WRTiytgkrr5dkQ/gtNdaT8LzAQknvj/qwTsMfL8bxgOQyZZj+I0XqBkg0WIMw/DfXxzzUAy3YSMu9taK0k+72Jur0ub4Xjx4S5ZuKZ4iQeyL0lgCT2e88EO1zeHxnE72aEseCHzLRe18V22xX8N0jftYXRq2Bv+3eVh48u7vsuc1SAQ7/r+Kd3HeyyT34+A1cZRdhwKBDZ1m4ly3P0a4LDdGEUsacSGjowg7XN3QtncksPwP52u8xKv5zLonD/9cCSkK7hWXc3sZaWnUUx0VYfTPoTWZiuY6SFaOwDzkqaaH/QUWxizCRwME+OBf/AdWsap8ByV2V0S4KTYy5zMLPjRpih3149ZFMdf8vj7na+gVq82qRgbBQZ7rR33+ivnHVeA7ednWqwIBorezQ3O1PDwAnsqPNGUgkvPDDKfcBIAWWYvQ4="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
     - |
       echo ""
@@ -38,14 +46,18 @@ install:
       echo ""
       echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --remove channels defaults
-      conda config --add channels defaults
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
